spring:
  resources:
    static-locations: classpath:/static/
server:
  port: 8001
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore/mewore-web.p12
    key-alias: mewore-web
    key-store-password: YBw3jEfUrdooeckPt1id
