spring:
  profiles:
    active:
      common
rabbit:
  diary:
    location: '/home/mewore/projects/2d/rabbits/done'
    auto-refresh:
      delay-ms: 5000 # Delay in milliseconds between each day
  page:
    path: 'rabbits/index.html'
    size: 10
